gh label create "status:ready" --color "0E8A16" --description "Spec complete, ready for implementation"
gh label create "status:in-progress" --color "FBCA04" --description "Claude Code is working on it"
gh label create "status:needs-clarification" --color "D93F0B" --description "Waiting on Cowork to answer questions"
gh label create "status:in-review" --color "1D76DB" --description "PR open, awaiting review"
gh label create "status:qa" --color "5319E7" --description "Code merged, QA pass needed"
gh label create "status:done" --color "C2E0C6" --description "Shipped"
gh label create "status:blocked" --color "B60205" --description "Blocked on external dependency"
gh label create "type:feature" --color "A2EEEF"
gh label create "type:bug" --color "EE0701"
gh label create "type:chore" --color "CCCCCC"
